name: docker-build-and-push
description: ""

inputs:
  bake-target:
    description: ""
    required: true
  bake-images:
    description: ""
    required: false
  build-args:
    description: ""
    required: false
  tag-prefix:
    description: ""
    required: false
  tag-suffix:
    description: ""
    required: false
  tag-arch:
    description: ""
    required: false
  allow-push:
    description: ""
    default: "true"
    required: false

runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set Docker tags
      id: set-docker-tags
      run: |
        tags=()
        if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref_type }}" == "tag" ]; then
            tags+=("$(echo "${{ github.ref }}" | sed -E 's/.*([vV][0-9]+\.[0-9]+\.[0-9]+).*/\1/')")
        fi

        tags+=("{{date 'YYYYMMDD'}}")
        tags+=("latest")
        tags+=("latest-${{ inputs.tag-prefix }}")

        # Output multiline strings: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "tags<<$EOF" >> $GITHUB_OUTPUT
        echo "$(printf "%s\n" "${tags[@]}")" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Docker meta for base
      id: meta-base
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-base
        flavor: |
          latest=false
          suffix=-base${{ inputs.tag-arch }}

    - name: Docker meta for prebuilt
      id: meta-prebuilt
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-prebuilt
        flavor: |
          latest=false
          suffix=-prebuilt${{ inputs.tag-suffix }}${{ inputs.tag-arch }}

    - name: Docker meta for devel
      id: meta-devel
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-devel
        flavor: |
          latest=false
          suffix=-devel${{ inputs.tag-suffix }}${{ inputs.tag-arch }}

    - name: Docker meta for runtime
      id: meta-runtime
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-runtime
        flavor: |
          latest=${{ github.event_name == 'push' && github.ref_type == 'tag' }}
          suffix=-runtime${{ inputs.tag-suffix }}${{ inputs.tag-arch }}

    - name: Login to GitHub Container Registry
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and Push to GitHub Container Registry
      if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || ( github.event_name == 'workflow_dispatch' && github.event.inputs.artifacts-destination == 'registry') }}
      uses: docker/bake-action@v3
      with:
        push: ${{ inputs.allow-push == 'true' }}
        files: |
          docker/docker-bake.hcl
          ${{ steps.meta-base.outputs.bake-file }}
          ${{ steps.meta-prebuilt.outputs.bake-file }}
          ${{ steps.meta-devel.outputs.bake-file }}
          ${{ steps.meta-runtime.outputs.bake-file }}
        provenance: false
        targets: |
          ${{ inputs.bake-images }}
        set: |
          ${{ inputs.build-args }}

    - name: Build Only
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.artifacts-destination == 'tarball' }}
      uses: docker/bake-action@v3
      with:
        push: false
        files: |
          docker/docker-bake.hcl
          ${{ steps.meta-base.outputs.bake-file }}
          ${{ steps.meta-prebuilt.outputs.bake-file }}
          ${{ steps.meta-devel.outputs.bake-file }}
          ${{ steps.meta-runtime.outputs.bake-file }}
        provenance: false
        targets: |
          ${{ inputs.bake-images }}
        set: |
          ${{ inputs.build-args }}